### ISSUE TITLE
`pip install flake8-bugbear` failed in python 2.7.12

### ISSUE THREAD

**Issue by number5** [ambv/flake8-bugbear#1]
Here is the backtrace:
```
λ pip install flake8-bugbear                                  ]
Collecting flake8-bugbear
  Downloading flake8-bugbear-16.7.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/t4/4r0q_f752vn1qr36pw1tq2280000gn/T/pip-build-mSeIFo/flake8-bugbear/setup.py", line 10, in <module>
        with open(os.path.join(current_dir, 'README.rst'), encoding='utf8') as ld_file:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/t4/4r0q_f752vn1qr36pw1tq2280000gn/T/pip-build-mSeIFo/flake8-bugbear/
```

**Comment by ambv** [comment]
bugbear is Python 3 only, it says so right in the readme.

-- 
Best regards,
Łukasz Langa

**Comment by number5** [comment]
oops, sorry.
