### ISSUE TITLE
doesn't install via pip

### ISSUE THREAD

**Issue by spaceone** [ambv/flake8-bugbear#6]
```
# pip install flake8-bugbear
Collecting flake8-bugbear
  Downloading flake8-bugbear-16.10.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-RE3yha/flake8-bugbear/setup.py", line 10, in <module>
        with open(os.path.join(current_dir, 'README.rst'), encoding='utf8') as ld_file:
    TypeError: 'encoding' is an invalid keyword argument for this function
```

**Comment by spaceone** [comment]
```
# python --version
Python 2.7.9
# pip --version
pip 8.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)
```

**Comment by untitaker** [comment]
https://github.com/ambv/flake8-bugbear#omg-this-is-python-3-only

**Comment by spaceone** [comment]
Well okay, then it shouln't be offered for pip2, right?

**Comment by untitaker** [comment]
How is it offered? There is only one package repo for all versions of Python.

**Comment by spaceone** [comment]
Oh, I thought one can specify dependencies/requirements in setup.py

**Comment by spaceone** [comment]
Otherwise if pip is not capable of such thing you could add to setup.py:
```
if __import__('sys').version_info.major < 3:
    raise RuntimeError('Only python 3 allowed')
```

**Comment by ambv** [comment]
OK, graceful assertion failure added in 16.11.0.
