### ISSUE TITLE
python3.4 compatiblity

### ISSUE THREAD

**Issue by spaceone** [ambv/flake8-bugbear#7]
It seems this project only supports python > 3.5 ?
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/flake8/checker.py", line 633, in _run_checks_from_queue
    checker.run_checks(results_queue, statistics_queue)
  File "/usr/local/lib/python3.4/dist-packages/flake8/checker.py", line 573, in run_checks
    self.run_ast_checks()
  File "/usr/local/lib/python3.4/dist-packages/flake8/checker.py", line 484, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/usr/local/lib/python3.4/dist-packages/bugbear.py", line 31, in run
    visitor.visit(self.tree)
  File "/usr/local/lib/python3.4/dist-packages/bugbear.py", line 82, in visit
    super().visit(node)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.4/ast.py", line 253, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.4/dist-packages/bugbear.py", line 82, in visit
    super().visit(node)
  File "/usr/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/local/lib/python3.4/dist-packages/bugbear.py", line 162, in visit_FunctionDef
    if isinstance(x, (ast.AsyncFunctionDef, ast.FunctionDef)):
AttributeError: 'module' object has no attribute 'AsyncFunctionDef'
```

**Comment by spaceone** [comment]
Quoting you ```
By making the code exclusively Python 3.5+, I'm able to focus on the quality of the checks and re-use all the nice features of the new releases (check out pathlib) instead of wasting cycles on Unicode compatiblity, etc.
```
Unfortionately this makes your code not being usable by me. (I have no python 2.5 in the next X years when debian doesn't support this). Would you consider adding 3.4 compatibility?

**Comment by ambv** [comment]
I'm sorry but no. I don't have any spare cycles to support legacy versions of the language and test that they work. The async/await syntax introduced in 3.5 is a big deal to me. More importantly, bugbear requires Python 3.5 to be able to *parse* source code that uses 3.5+ syntax.

Would you consider [building a 3.5](https://www.python.org/downloads/source/) to use for your linting needs? It would literally take you less time to do that than to file this bug.

**Comment by spaceone** [comment]
Okay.

**Comment by spaceone** [comment]
(We are still on 2.7 and this will probably not change in the next 2 years). But okay, I think I will just check our code manually once when I set up a 3.5 environment.

**Comment by ambv** [comment]
flake8 is an external tool, you can keep it in an external virtual environment and just have it on PATH.
